[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "Source Code/backend"

[services.build]
buildCommand = "npm install && npx prisma generate && npm run build"
startCommand = "npm start"

[services.variables]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "frontend"
source = "Source Code/frontend"

[services.build]
buildCommand = "npm install && npm run build"
startCommand = "npm run start"

[services.variables]
NODE_ENV = "production"